/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/m5_arrays/m5_arrays.rdl
 * DO NOT EDIT
 */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "qapi/error.h"
#include "hw/register.h"
#include "hw/resettable.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "hw/misc/m5_arrays.h"

#ifndef M5_ARRAYS_ERR_DEBUG
#define M5_ARRAYS_ERR_DEBUG 0
#endif

static void gen_data_0_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_data_0_write(s, (uint32_t)val);
}

static void gen_data_1_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_data_1_write(s, (uint32_t)val);
}

static void gen_data_2_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_data_2_write(s, (uint32_t)val);
}

static void gen_data_3_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_data_3_write(s, (uint32_t)val);
}

static void gen_grp_r0_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_grp_r0_write(s, (uint32_t)val);
}

static void gen_grp_r1_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_grp_r1_write(s, (uint32_t)val);
}

static void gen_bank_0_v_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_bank_0_v_write(s, (uint32_t)val);
}

static void gen_bank_1_v_post_write(RegisterInfo *reg, uint64_t val)
{
    M5ArraysState *s = M5_ARRAYS(reg->opaque);

    m5_arrays_bank_1_v_write(s, (uint32_t)val);
}

static const RegisterAccessInfo m5_arrays_regs_info[] = {
    {   .name = "DATA_0",
        .addr = A_DATA_0,
        .post_write = gen_data_0_post_write,
    },
    {   .name = "DATA_1",
        .addr = A_DATA_1,
        .post_write = gen_data_1_post_write,
    },
    {   .name = "DATA_2",
        .addr = A_DATA_2,
        .post_write = gen_data_2_post_write,
    },
    {   .name = "DATA_3",
        .addr = A_DATA_3,
        .post_write = gen_data_3_post_write,
    },
    {   .name = "GRP_R0",
        .addr = A_GRP_R0,
        .post_write = gen_grp_r0_post_write,
    },
    {   .name = "GRP_R1",
        .addr = A_GRP_R1,
        .post_write = gen_grp_r1_post_write,
    },
    {   .name = "BANK_0_V",
        .addr = A_BANK_0_V,
        .post_write = gen_bank_0_v_post_write,
    },
    {   .name = "BANK_1_V",
        .addr = A_BANK_1_V,
        .post_write = gen_bank_1_v_post_write,
    }
};

static const MemoryRegionOps m5_arrays_ops = {
    .read = register_read_memory,
    .write = register_write_memory,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
};

static void m5_arrays_reset_hold(Object *obj, ResetType type)
{
    M5ArraysState *s = M5_ARRAYS(obj);
    unsigned int i;

    (void)type;
    for (i = 0; i < ARRAY_SIZE(s->regs_info); i++) {
        register_reset(&s->regs_info[i]);
    }

    m5_arrays_behavior_reset(s);
}

static void m5_arrays_realize(DeviceState *dev, Error **errp)
{
    M5ArraysState *s = M5_ARRAYS(dev);

    (void)errp;

    /* Child buses (I2C, ...) will be created here in later milestones. */
    m5_arrays_behavior_init(s);
}

static void m5_arrays_init(Object *obj)
{
    M5ArraysState *s = M5_ARRAYS(obj);
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);

    memory_region_init(&s->iomem, obj, TYPE_M5_ARRAYS,
                       M5_ARRAYS_MMIO_SIZE);
    s->reg_array =
        register_init_block32(DEVICE(obj), m5_arrays_regs_info,
                              ARRAY_SIZE(m5_arrays_regs_info),
                              s->regs_info, s->regs,
                              &m5_arrays_ops,
                              M5_ARRAYS_ERR_DEBUG,
                              M5_ARRAYS_MMIO_SIZE);
    memory_region_add_subregion(&s->iomem, 0x0, &s->reg_array->mem);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription vmstate_m5_arrays = {
    .name = TYPE_M5_ARRAYS,
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (const VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, M5ArraysState, M5_ARRAYS_R_MAX),
        VMSTATE_END_OF_LIST(),
    },
#ifdef M5_ARRAYS_BEHAVIOR_HAS_VMSTATE
    .subsections = (const VMStateDescription * const []) {
        &vmstate_m5_arrays_behavior,
        NULL
    },
#endif
};

static void m5_arrays_class_init(ObjectClass *klass, const void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    ResettableClass *rc = RESETTABLE_CLASS(klass);

    (void)data;
    dc->realize = m5_arrays_realize;
    dc->vmsd = &vmstate_m5_arrays;
    rc->phases.hold = m5_arrays_reset_hold;
}

static const TypeInfo m5_arrays_info = {
    .name = TYPE_M5_ARRAYS,
    .parent = TYPE_SYS_BUS_DEVICE,
    .instance_size = sizeof(M5ArraysState),
    .instance_init = m5_arrays_init,
    .class_init = m5_arrays_class_init,
};

static void m5_arrays_register_types(void)
{
    type_register_static(&m5_arrays_info);
}

type_init(m5_arrays_register_types)
