#ifndef M5_ARRAYS_REGS_H
#define M5_ARRAYS_REGS_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/m5_arrays/m5_arrays.rdl
 * DO NOT EDIT
 */

#include "hw/register.h"

/*
 * DATA_0: DATA
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(DATA_0, 0x0)
    FIELD(DATA_0, VALUE, 0, 32)
/*
 * DATA_1: DATA
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(DATA_1, 0x4)
    FIELD(DATA_1, VALUE, 0, 32)
/*
 * DATA_2: DATA
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(DATA_2, 0x8)
    FIELD(DATA_2, VALUE, 0, 32)
/*
 * DATA_3: DATA
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(DATA_3, 0xc)
    FIELD(DATA_3, VALUE, 0, 32)
/*
 * GRP_R0: R0
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(GRP_R0, 0x100)
    FIELD(GRP_R0, A, 0, 32)
/*
 * GRP_R1: R1
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(GRP_R1, 0x104)
    FIELD(GRP_R1, B, 0, 32)
/*
 * BANK_0_V: V
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(BANK_0_V, 0x200)
    FIELD(BANK_0_V, X, 0, 32)
/*
 * BANK_1_V: V
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(BANK_1_V, 0x210)
    FIELD(BANK_1_V, X, 0, 32)

#define M5_ARRAYS_R_MAX 136
#define M5_ARRAYS_MMIO_SIZE 0x220

#endif /* M5_ARRAYS_REGS_H */
