#ifndef M5_ARRAYS_H
#define M5_ARRAYS_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/m5_arrays/m5_arrays.rdl
 * DO NOT EDIT
 */

#include "hw/sysbus.h"
#include "hw/register.h"
#include "hw/misc/m5_arrays_regs.h"
#include "hw/misc/m5_arrays_behavior.h"

#define TYPE_M5_ARRAYS "m5-arrays"
OBJECT_DECLARE_SIMPLE_TYPE(M5ArraysState, M5_ARRAYS)

struct M5ArraysState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    RegisterInfoArray *reg_array;

    uint32_t regs[M5_ARRAYS_R_MAX];
    RegisterInfo regs_info[M5_ARRAYS_R_MAX];

    M5ArraysBehavior bh;
};

/*
 * Hook contract -- implemented in m5_arrays_behavior.c
 *
 * A missing hook is a link error. This is intended.
 */
void m5_arrays_behavior_init(M5ArraysState *s);
void m5_arrays_behavior_reset(M5ArraysState *s);
void m5_arrays_data_0_write(M5ArraysState *s, uint32_t val);
void m5_arrays_data_1_write(M5ArraysState *s, uint32_t val);
void m5_arrays_data_2_write(M5ArraysState *s, uint32_t val);
void m5_arrays_data_3_write(M5ArraysState *s, uint32_t val);
void m5_arrays_grp_r0_write(M5ArraysState *s, uint32_t val);
void m5_arrays_grp_r1_write(M5ArraysState *s, uint32_t val);
void m5_arrays_bank_0_v_write(M5ArraysState *s, uint32_t val);
void m5_arrays_bank_1_v_write(M5ArraysState *s, uint32_t val);

#endif /* M5_ARRAYS_H */
