#ifndef OCORES_I2C_H
#define OCORES_I2C_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/ocores_i2c/ocores_i2c.rdl
 * DO NOT EDIT
 */

#include "hw/sysbus.h"
#include "hw/register.h"
#include "hw/i2c/ocores_i2c_regs.h"
#include "hw/i2c/ocores_i2c_behavior.h"

#define TYPE_OCORES_I2C "ocores-i2c"
OBJECT_DECLARE_SIMPLE_TYPE(OcoresI2cState, OCORES_I2C)

struct OcoresI2cState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    qemu_irq irq[1];
    RegisterInfoArray *reg_array;

    uint32_t regs[OCORES_I2C_R_MAX];
    RegisterInfo regs_info[OCORES_I2C_R_MAX];
    uint32_t shadow_rxr;
    uint32_t shadow_sr;

    OcoresI2cBehavior bh;
};

/*
 * Hook contract -- implemented in ocores_i2c_behavior.c
 *
 * A missing hook is a link error. This is intended.
 */
void ocores_i2c_behavior_init(OcoresI2cState *s);
void ocores_i2c_behavior_reset(OcoresI2cState *s);
void ocores_i2c_ctr_write(OcoresI2cState *s, uint32_t val);
void ocores_i2c_cr_write(OcoresI2cState *s, uint32_t val);

#endif /* OCORES_I2C_H */
