/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/ocores_i2c/ocores_i2c.rdl
 * DO NOT EDIT
 */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "qapi/error.h"
#include "hw/register.h"
#include "hw/resettable.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "hw/i2c/ocores_i2c.h"

#ifndef OCORES_I2C_ERR_DEBUG
#define OCORES_I2C_ERR_DEBUG 0
#endif

static void gen_ctr_post_write(RegisterInfo *reg, uint64_t val)
{
    OcoresI2cState *s = OCORES_I2C(reg->opaque);

    ocores_i2c_ctr_write(s, (uint32_t)val);
}

static uint64_t gen_txr_post_read(RegisterInfo *reg, uint64_t val)
{
    OcoresI2cState *s = OCORES_I2C(reg->opaque);
    uint32_t ret = (uint32_t)val;

    ret = s->shadow_rxr;
    return ret;
}

static void gen_cr_post_write(RegisterInfo *reg, uint64_t val)
{
    OcoresI2cState *s = OCORES_I2C(reg->opaque);

    ocores_i2c_cr_write(s, (uint32_t)val);
    s->regs[R_CR] &= ~0x000000f1;
}

static uint64_t gen_cr_post_read(RegisterInfo *reg, uint64_t val)
{
    OcoresI2cState *s = OCORES_I2C(reg->opaque);
    uint32_t ret = (uint32_t)val;

    ret = s->shadow_sr;
    return ret;
}

static const RegisterAccessInfo ocores_i2c_regs_info[] = {
    {   .name = "PRERLO",
        .addr = A_PRERLO,
        .reset = 0x000000ff,
        .ro = 0xffffff00,
        .rsvd = 0xffffff00,
    },
    {   .name = "PRERHI",
        .addr = A_PRERHI,
        .reset = 0x000000ff,
        .ro = 0xffffff00,
        .rsvd = 0xffffff00,
    },
    {   .name = "CTR",
        .addr = A_CTR,
        .ro = 0xffffff3f,
        .rsvd = 0xffffff3f,
        .post_write = gen_ctr_post_write,
    },
    {   .name = "TXR_RXR",
        .addr = A_TXR,
        .ro = 0xffffff00,
        .rsvd = 0xffffff00,
        .post_read = gen_txr_post_read,
    },
    {   .name = "CR_SR",
        .addr = A_CR,
        .ro = 0xffffff06,
        .rsvd = 0xffffff06,
        .post_write = gen_cr_post_write,
        .post_read = gen_cr_post_read,
    }
};

static const MemoryRegionOps ocores_i2c_ops = {
    .read = register_read_memory,
    .write = register_write_memory,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
};

static void ocores_i2c_reset_hold(Object *obj, ResetType type)
{
    OcoresI2cState *s = OCORES_I2C(obj);
    unsigned int i;

    (void)type;
    for (i = 0; i < ARRAY_SIZE(s->regs_info); i++) {
        register_reset(&s->regs_info[i]);
    }
    s->shadow_rxr = 0x00000000;
    s->shadow_sr = 0x00000000;

    ocores_i2c_behavior_reset(s);
}

static void ocores_i2c_realize(DeviceState *dev, Error **errp)
{
    OcoresI2cState *s = OCORES_I2C(dev);

    (void)errp;

    /* Child buses (I2C, ...) will be created here in later milestones. */
    ocores_i2c_behavior_init(s);
}

static void ocores_i2c_init(Object *obj)
{
    OcoresI2cState *s = OCORES_I2C(obj);
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    int i;

    memory_region_init(&s->iomem, obj, TYPE_OCORES_I2C,
                       OCORES_I2C_MMIO_SIZE);
    s->reg_array =
        register_init_block32(DEVICE(obj), ocores_i2c_regs_info,
                              ARRAY_SIZE(ocores_i2c_regs_info),
                              s->regs_info, s->regs,
                              &ocores_i2c_ops,
                              OCORES_I2C_ERR_DEBUG,
                              OCORES_I2C_MMIO_SIZE);
    memory_region_add_subregion(&s->iomem, 0x0, &s->reg_array->mem);
    sysbus_init_mmio(sbd, &s->iomem);
    for (i = 0; i < 1; i++) {
        sysbus_init_irq(sbd, &s->irq[i]);
    }
}

static const VMStateDescription vmstate_ocores_i2c = {
    .name = TYPE_OCORES_I2C,
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (const VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, OcoresI2cState, OCORES_I2C_R_MAX),
        VMSTATE_UINT32(shadow_rxr, OcoresI2cState),
        VMSTATE_UINT32(shadow_sr, OcoresI2cState),
        VMSTATE_END_OF_LIST(),
    },
#ifdef OCORES_I2C_BEHAVIOR_HAS_VMSTATE
    .subsections = (const VMStateDescription * const []) {
        &vmstate_ocores_i2c_behavior,
        NULL
    },
#endif
};

static void ocores_i2c_class_init(ObjectClass *klass, const void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    ResettableClass *rc = RESETTABLE_CLASS(klass);

    (void)data;
    dc->realize = ocores_i2c_realize;
    dc->vmsd = &vmstate_ocores_i2c;
    rc->phases.hold = ocores_i2c_reset_hold;
}

static const TypeInfo ocores_i2c_info = {
    .name = TYPE_OCORES_I2C,
    .parent = TYPE_SYS_BUS_DEVICE,
    .instance_size = sizeof(OcoresI2cState),
    .instance_init = ocores_i2c_init,
    .class_init = ocores_i2c_class_init,
};

static void ocores_i2c_register_types(void)
{
    type_register_static(&ocores_i2c_info);
}

type_init(ocores_i2c_register_types)
