#ifndef OCORES_I2C_REGS_H
#define OCORES_I2C_REGS_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/ocores_i2c/ocores_i2c.rdl
 * DO NOT EDIT
 */

#include "hw/register.h"

/*
 * PRERLO: PRERLO
 * reset: 0x000000ff
 * hardware-writable fields: (none)
 */
REG32(PRERLO, 0x0)
    FIELD(PRERLO, PRE, 0, 8)
/*
 * PRERHI: PRERHI
 * reset: 0x000000ff
 * hardware-writable fields: (none)
 */
REG32(PRERHI, 0x4)
    FIELD(PRERHI, PRE, 0, 8)
/*
 * CTR: CTR
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(CTR, 0x8)
    FIELD(CTR, IEN, 6, 1)
    FIELD(CTR, EN, 7, 1)
/*
 * TXR: TXR
 * reset: 0x00000000
 * hardware-writable fields: (none)
 * shared pair with RXR (read-side shadow shadow_rxr)
 */
REG32(TXR, 0xc)
    FIELD(TXR, DATA, 0, 8)
/*
 * RXR (read side of shared pair, no REG32)
 * reset: 0x00000000
 * hardware-writable fields: DATA
 */
    FIELD(RXR, DATA, 0, 8)
/*
 * CR: CR
 * reset: 0x00000000
 * hardware-writable fields: (none)
 * shared pair with SR (read-side shadow shadow_sr)
 */
REG32(CR, 0x10)
    FIELD(CR, IACK, 0, 1)
    FIELD(CR, ACK, 3, 1)
    FIELD(CR, WR, 4, 1)
    FIELD(CR, RD, 5, 1)
    FIELD(CR, STO, 6, 1)
    FIELD(CR, STA, 7, 1)
/*
 * SR (read side of shared pair, no REG32)
 * reset: 0x00000000
 * hardware-writable fields: IF, TIP, AL, BUSY, RXACK
 */
    FIELD(SR, IF, 0, 1)
    FIELD(SR, TIP, 1, 1)
    FIELD(SR, AL, 5, 1)
    FIELD(SR, BUSY, 6, 1)
    FIELD(SR, RXACK, 7, 1)

#define OCORES_I2C_R_MAX 5
#define OCORES_I2C_MMIO_SIZE 0x14

#endif /* OCORES_I2C_REGS_H */
