/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/m3_features/m3_features.rdl
 * DO NOT EDIT
 */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "qapi/error.h"
#include "hw/register.h"
#include "hw/resettable.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "hw/misc/m3_features.h"

#ifndef M3_FEATURES_ERR_DEBUG
#define M3_FEATURES_ERR_DEBUG 0
#endif

static void gen_mixed_post_write(RegisterInfo *reg, uint64_t val)
{
    M3FeaturesState *s = M3_FEATURES(reg->opaque);

    m3_features_mixed_write(s, (uint32_t)val);
}

static uint64_t gen_mixed_post_read(RegisterInfo *reg, uint64_t val)
{
    uint32_t ret = (uint32_t)val;
    (void)reg;

    ret &= ~0x0000ff00;
    return ret;
}

static uint64_t gen_woset_pre_write(RegisterInfo *reg, uint64_t val)
{
    uint32_t old = *(uint32_t *)reg->data;
    uint32_t newv = (uint32_t)val;

    /* woset: writing 1 sets, writing 0 has no effect */
    newv |= old & 0x00000001;
    return newv;
}

static void gen_woset_post_write(RegisterInfo *reg, uint64_t val)
{
    M3FeaturesState *s = M3_FEATURES(reg->opaque);

    m3_features_woset_write(s, (uint32_t)val);
}

static uint64_t gen_rset_post_read(RegisterInfo *reg, uint64_t val)
{
    M3FeaturesState *s = M3_FEATURES(reg->opaque);
    uint32_t ret = (uint32_t)val;

    s->regs[R_RSET] |= 0x00000001;
    return ret;
}

static void gen_txr_post_write(RegisterInfo *reg, uint64_t val)
{
    M3FeaturesState *s = M3_FEATURES(reg->opaque);

    m3_features_txr_write(s, (uint32_t)val);
}

static uint64_t gen_txr_post_read(RegisterInfo *reg, uint64_t val)
{
    M3FeaturesState *s = M3_FEATURES(reg->opaque);
    uint32_t ret = (uint32_t)val;

    ret = s->shadow_rxr;
    return ret;
}

static void gen_cr_post_write(RegisterInfo *reg, uint64_t val)
{
    M3FeaturesState *s = M3_FEATURES(reg->opaque);

    m3_features_cr_write(s, (uint32_t)val);
    s->regs[R_CR] &= ~0x00000001;
}

static const RegisterAccessInfo m3_features_regs_info[] = {
    {   .name = "MIXED",
        .addr = A_MIXED,
        .ro = 0xffff00fe,
        .rsvd = 0xffff00fe,
        .post_write = gen_mixed_post_write,
        .post_read = gen_mixed_post_read,
    },
    {   .name = "WOSET",
        .addr = A_WOSET,
        .ro = 0xfffffffe,
        .rsvd = 0xfffffffe,
        .pre_write = gen_woset_pre_write,
        .post_write = gen_woset_post_write,
    },
    {   .name = "RSET",
        .addr = A_RSET,
        .ro = 0xffffffff,
        .rsvd = 0xfffffffe,
        .post_read = gen_rset_post_read,
    },
    {   .name = "TXR_RXR",
        .addr = A_TXR,
        .ro = 0xffffff00,
        .rsvd = 0xffffff00,
        .post_write = gen_txr_post_write,
        .post_read = gen_txr_post_read,
    },
    {   .name = "CR",
        .addr = A_CR,
        .ro = 0xffffff7e,
        .rsvd = 0xffffff7e,
        .post_write = gen_cr_post_write,
    }
};

static const MemoryRegionOps m3_features_ops = {
    .read = register_read_memory,
    .write = register_write_memory,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
};

static void m3_features_reset_hold(Object *obj, ResetType type)
{
    M3FeaturesState *s = M3_FEATURES(obj);
    unsigned int i;

    (void)type;
    for (i = 0; i < ARRAY_SIZE(s->regs_info); i++) {
        register_reset(&s->regs_info[i]);
    }
    s->shadow_rxr = 0x00000000;

    m3_features_behavior_reset(s);
}

static void m3_features_realize(DeviceState *dev, Error **errp)
{
    M3FeaturesState *s = M3_FEATURES(dev);

    (void)errp;

    /* Child buses (I2C, ...) will be created here in later milestones. */
    m3_features_behavior_init(s);
}

static void m3_features_init(Object *obj)
{
    M3FeaturesState *s = M3_FEATURES(obj);
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);

    memory_region_init(&s->iomem, obj, TYPE_M3_FEATURES,
                       M3_FEATURES_MMIO_SIZE);
    s->reg_array =
        register_init_block32(DEVICE(obj), m3_features_regs_info,
                              ARRAY_SIZE(m3_features_regs_info),
                              s->regs_info, s->regs,
                              &m3_features_ops,
                              M3_FEATURES_ERR_DEBUG,
                              M3_FEATURES_MMIO_SIZE);
    memory_region_add_subregion(&s->iomem, 0x0, &s->reg_array->mem);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription vmstate_m3_features = {
    .name = TYPE_M3_FEATURES,
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (const VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, M3FeaturesState, M3_FEATURES_R_MAX),
        VMSTATE_UINT32(shadow_rxr, M3FeaturesState),
        VMSTATE_END_OF_LIST(),
    },
#ifdef M3_FEATURES_BEHAVIOR_HAS_VMSTATE
    .subsections = (const VMStateDescription * const []) {
        &vmstate_m3_features_behavior,
        NULL
    },
#endif
};

static void m3_features_class_init(ObjectClass *klass, const void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    ResettableClass *rc = RESETTABLE_CLASS(klass);

    (void)data;
    dc->realize = m3_features_realize;
    dc->vmsd = &vmstate_m3_features;
    rc->phases.hold = m3_features_reset_hold;
}

static const TypeInfo m3_features_info = {
    .name = TYPE_M3_FEATURES,
    .parent = TYPE_SYS_BUS_DEVICE,
    .instance_size = sizeof(M3FeaturesState),
    .instance_init = m3_features_init,
    .class_init = m3_features_class_init,
};

static void m3_features_register_types(void)
{
    type_register_static(&m3_features_info);
}

type_init(m3_features_register_types)
