#ifndef M3_FEATURES_REGS_H
#define M3_FEATURES_REGS_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/m3_features/m3_features.rdl
 * DO NOT EDIT
 */

#include "hw/register.h"

/*
 * MIXED: Mixed write-only
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(MIXED, 0x0)
    FIELD(MIXED, EN, 0, 1)
    FIELD(MIXED, DATA, 8, 8)
/*
 * WOSET: Write-one-to-set
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(WOSET, 0x4)
    FIELD(WOSET, FLAG, 0, 1)
/*
 * RSET: Read-set
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(RSET, 0x8)
    FIELD(RSET, FLAG, 0, 1)
/*
 * TXR: Transmit
 * reset: 0x00000000
 * hardware-writable fields: (none)
 * shared pair with RXR (read-side shadow shadow_rxr)
 */
REG32(TXR, 0xc)
    FIELD(TXR, DATA, 0, 8)
/*
 * RXR (read side of shared pair, no REG32)
 * reset: 0x00000000
 * hardware-writable fields: DATA
 */
    FIELD(RXR, DATA, 0, 8)
/*
 * CR: Command
 * reset: 0x00000000
 * hardware-writable fields: (none)
 */
REG32(CR, 0x10)
    FIELD(CR, GO, 0, 1)
    FIELD(CR, ACK, 7, 1)

#define M3_FEATURES_R_MAX 5
#define M3_FEATURES_MMIO_SIZE 0x14

#endif /* M3_FEATURES_REGS_H */
