#ifndef M3_FEATURES_H
#define M3_FEATURES_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/m3_features/m3_features.rdl
 * DO NOT EDIT
 */

#include "hw/sysbus.h"
#include "hw/register.h"
#include "hw/misc/m3_features_regs.h"
#include "hw/misc/m3_features_behavior.h"

#define TYPE_M3_FEATURES "m3-features"
OBJECT_DECLARE_SIMPLE_TYPE(M3FeaturesState, M3_FEATURES)

struct M3FeaturesState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    RegisterInfoArray *reg_array;

    uint32_t regs[M3_FEATURES_R_MAX];
    RegisterInfo regs_info[M3_FEATURES_R_MAX];
    uint32_t shadow_rxr;

    M3FeaturesBehavior bh;
};

/*
 * Hook contract -- implemented in m3_features_behavior.c
 *
 * A missing hook is a link error. This is intended.
 */
void m3_features_behavior_init(M3FeaturesState *s);
void m3_features_behavior_reset(M3FeaturesState *s);
void m3_features_mixed_write(M3FeaturesState *s, uint32_t val);
void m3_features_woset_write(M3FeaturesState *s, uint32_t val);
void m3_features_txr_write(M3FeaturesState *s, uint32_t val);
void m3_features_cr_write(M3FeaturesState *s, uint32_t val);

#endif /* M3_FEATURES_H */
