#ifndef SIMPLE_TIMER_REGS_H
#define SIMPLE_TIMER_REGS_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/simple_timer/simple_timer.rdl
 * DO NOT EDIT
 */

#include "hw/register.h"

/*
 * CTRL: Control
 * reset: 0x00001000
 * hardware-writable fields: (none)
 */
REG32(CTRL, 0x0)
    FIELD(CTRL, EN, 0, 1)
    FIELD(CTRL, IRQ_EN, 1, 1)
    FIELD(CTRL, PRESCALE, 8, 8)
/*
 * LOAD: Load
 * reset: 0xffffffff
 * hardware-writable fields: (none)
 */
REG32(LOAD, 0x4)
    FIELD(LOAD, VALUE, 0, 32)
/*
 * COUNT: Count
 * reset: 0x00000000
 * hardware-writable fields: VALUE
 */
REG32(COUNT, 0x8)
    FIELD(COUNT, VALUE, 0, 32)
/*
 * STATUS: Status
 * reset: 0x00000000
 * hardware-writable fields: EXPIRED, OVERRUN
 */
REG32(STATUS, 0xc)
    FIELD(STATUS, EXPIRED, 0, 1)
    FIELD(STATUS, OVERRUN, 1, 1)
/*
 * ID: ID
 * reset: 0x54494d52
 * hardware-writable fields: (none)
 */
REG32(ID, 0x10)
    FIELD(ID, ID, 0, 32)

#define SIMPLE_TIMER_R_MAX 5
#define SIMPLE_TIMER_MMIO_SIZE 0x14

#endif /* SIMPLE_TIMER_REGS_H */
