/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/simple_timer/simple_timer.rdl
 * DO NOT EDIT
 */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "qapi/error.h"
#include "hw/register.h"
#include "hw/resettable.h"
#include "hw/sysbus.h"
#include "migration/vmstate.h"
#include "hw/misc/simple_timer.h"

#ifndef SIMPLE_TIMER_ERR_DEBUG
#define SIMPLE_TIMER_ERR_DEBUG 0
#endif

static void gen_ctrl_post_write(RegisterInfo *reg, uint64_t val)
{
    SimpleTimerState *s = SIMPLE_TIMER(reg->opaque);

    simple_timer_ctrl_write(s, (uint32_t)val);
}

static void gen_load_post_write(RegisterInfo *reg, uint64_t val)
{
    SimpleTimerState *s = SIMPLE_TIMER(reg->opaque);

    simple_timer_load_write(s, (uint32_t)val);
}

static void gen_status_post_write(RegisterInfo *reg, uint64_t val)
{
    SimpleTimerState *s = SIMPLE_TIMER(reg->opaque);

    simple_timer_status_write(s, (uint32_t)val);
}

static const RegisterAccessInfo simple_timer_regs_info[] = {
    {   .name = "CTRL",
        .addr = A_CTRL,
        .reset = 0x00001000,
        .ro = 0xffff00fc,
        .rsvd = 0xffff00fc,
        .post_write = gen_ctrl_post_write,
    },
    {   .name = "LOAD",
        .addr = A_LOAD,
        .reset = 0xffffffff,
        .post_write = gen_load_post_write,
    },
    {   .name = "COUNT",
        .addr = A_COUNT,
        .ro = 0xffffffff,
    },
    {   .name = "STATUS",
        .addr = A_STATUS,
        .ro = 0xfffffffe,
        .w1c = 0x00000001,
        .cor = 0x00000002,
        .rsvd = 0xfffffffc,
        .post_write = gen_status_post_write,
    },
    {   .name = "ID",
        .addr = A_ID,
        .reset = 0x54494d52,
        .ro = 0xffffffff,
    }
};

static const MemoryRegionOps simple_timer_ops = {
    .read = register_read_memory,
    .write = register_write_memory,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
};

static void simple_timer_reset_hold(Object *obj, ResetType type)
{
    SimpleTimerState *s = SIMPLE_TIMER(obj);
    unsigned int i;

    (void)type;
    for (i = 0; i < ARRAY_SIZE(s->regs_info); i++) {
        register_reset(&s->regs_info[i]);
    }

    simple_timer_behavior_reset(s);
}

static void simple_timer_realize(DeviceState *dev, Error **errp)
{
    SimpleTimerState *s = SIMPLE_TIMER(dev);

    (void)errp;

    /* Child buses (I2C, ...) will be created here in later milestones. */
    simple_timer_behavior_init(s);
}

static void simple_timer_init(Object *obj)
{
    SimpleTimerState *s = SIMPLE_TIMER(obj);
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);
    int i;

    memory_region_init(&s->iomem, obj, TYPE_SIMPLE_TIMER,
                       SIMPLE_TIMER_MMIO_SIZE);
    s->reg_array =
        register_init_block32(DEVICE(obj), simple_timer_regs_info,
                              ARRAY_SIZE(simple_timer_regs_info),
                              s->regs_info, s->regs,
                              &simple_timer_ops,
                              SIMPLE_TIMER_ERR_DEBUG,
                              SIMPLE_TIMER_MMIO_SIZE);
    memory_region_add_subregion(&s->iomem, 0x0, &s->reg_array->mem);
    sysbus_init_mmio(sbd, &s->iomem);
    for (i = 0; i < 1; i++) {
        sysbus_init_irq(sbd, &s->irq[i]);
    }
}

static const VMStateDescription vmstate_simple_timer = {
    .name = TYPE_SIMPLE_TIMER,
    .version_id = 1,
    .minimum_version_id = 1,
    .fields = (const VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, SimpleTimerState, SIMPLE_TIMER_R_MAX),
        VMSTATE_END_OF_LIST(),
    },
#ifdef SIMPLE_TIMER_BEHAVIOR_HAS_VMSTATE
    .subsections = (const VMStateDescription * const []) {
        &vmstate_simple_timer_behavior,
        NULL
    },
#endif
};

static void simple_timer_class_init(ObjectClass *klass, const void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    ResettableClass *rc = RESETTABLE_CLASS(klass);

    (void)data;
    dc->realize = simple_timer_realize;
    dc->vmsd = &vmstate_simple_timer;
    rc->phases.hold = simple_timer_reset_hold;
}

static const TypeInfo simple_timer_info = {
    .name = TYPE_SIMPLE_TIMER,
    .parent = TYPE_SYS_BUS_DEVICE,
    .instance_size = sizeof(SimpleTimerState),
    .instance_init = simple_timer_init,
    .class_init = simple_timer_class_init,
};

static void simple_timer_register_types(void)
{
    type_register_static(&simple_timer_info);
}

type_init(simple_timer_register_types)
