#ifndef SIMPLE_TIMER_H
#define SIMPLE_TIMER_H

/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * GENERATED by peakrdl-qemu v0.1.0 from examples/simple_timer/simple_timer.rdl
 * DO NOT EDIT
 */

#include "hw/sysbus.h"
#include "hw/register.h"
#include "hw/misc/simple_timer_regs.h"
#include "hw/misc/simple_timer_behavior.h"

#define TYPE_SIMPLE_TIMER "simple-timer"
OBJECT_DECLARE_SIMPLE_TYPE(SimpleTimerState, SIMPLE_TIMER)

struct SimpleTimerState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    qemu_irq irq[1];
    RegisterInfoArray *reg_array;

    uint32_t regs[SIMPLE_TIMER_R_MAX];
    RegisterInfo regs_info[SIMPLE_TIMER_R_MAX];

    SimpleTimerBehavior bh;
};

/*
 * Hook contract -- implemented in simple_timer_behavior.c
 *
 * A missing hook is a link error. This is intended.
 */
void simple_timer_behavior_init(SimpleTimerState *s);
void simple_timer_behavior_reset(SimpleTimerState *s);
void simple_timer_ctrl_write(SimpleTimerState *s, uint32_t val);
void simple_timer_load_write(SimpleTimerState *s, uint32_t val);
void simple_timer_status_write(SimpleTimerState *s, uint32_t val);

#endif /* SIMPLE_TIMER_H */
